import os
import httpx
import google.generativeai as genai
from fastapi import FastAPI, Request, status
from fastapi.responses import RedirectResponse, JSONResponse, FileResponse
from dotenv import load_dotenv
from authlib.integrations.starlette_client import OAuth
from starlette.middleware.sessions import SessionMiddleware

load_dotenv()
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '0'

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
ai_model = genai.GenerativeModel('models/gemini-flash-latest')

# --- Update 1: Brand New App Title ---
app = FastAPI(title="Aegis-Agent | Secure Authorized Execution")

app.add_middleware(
    SessionMiddleware,
    secret_key=os.getenv("AUTH0_SECRET"),
    same_site="lax",
    https_only=True
)

oauth = OAuth()
oauth.register(
    "auth0",
    client_id=os.getenv("AUTH0_CLIENT_ID"),
    client_secret=os.getenv("AUTH0_CLIENT_SECRET"),
    client_kwargs={"scope": "openid profile email repo"},
    server_metadata_url=f'https://{os.getenv("AUTH0_DOMAIN")}/.well-known/openid-configuration',
)

async def get_github_token(user_id: str):
    domain = os.getenv("AUTH0_DOMAIN")
    async with httpx.AsyncClient() as client:
        token_res = await client.post(
            f"https://{domain}/oauth/token",
            json={
                "client_id": os.getenv("AUTH0_CLIENT_ID"),
                "client_secret": os.getenv("AUTH0_CLIENT_SECRET"),
                "audience": f"https://{domain}/api/v2/",
                "grant_type": "client_credentials"
            }
        )
        mgmt_token = token_res.json().get("access_token")
        user_res = await client.get(
            f"https://{domain}/api/v2/users/{user_id}",
            headers={"Authorization": f"Bearer {mgmt_token}"}
        )
        for identity in user_res.json().get("identities", []):
            if identity.get("provider") == "github":
                return identity.get("access_token")
    return None

@app.get("/ui")
def serve_ui():
    return FileResponse("../frontend/index.html")

@app.get("/")
def check_status(request: Request):
    user = request.session.get("user")
    if user:
        return {"status": "logged_in", "name": user["name"]}
    return JSONResponse({"status": "unauthorized"}, status_code=401)

@app.get("/login")
async def login(request: Request):
    return await oauth.auth0.authorize_redirect(
        request, redirect_uri=os.getenv("AUTH0_CALLBACK_URL"), connection="github"
    )

@app.get("/callback")
async def callback(request: Request):
    token = await oauth.auth0.authorize_access_token(request)
    if token.get("userinfo"):
        request.session["user"] = token.get("userinfo")
    return RedirectResponse(url="/ui")

@app.get("/ask-agent")
async def ask_agent(request: Request, prompt: str):
    user = request.session.get("user")
    if not user: return {"error": "Aegis-Agent requires unauthorized identity to proceed."}

    token = await get_github_token(user.get("sub"))
    
    # Retrieve latest repos with pushed date sorting
    async with httpx.AsyncClient() as client:
        repos_res = await client.get(
            "https://api.github.com/user/repos?sort=pushed&direction=desc",
            headers={"Authorization": f"token {token}"}
        )
        repos_data = repos_res.json()
        repos_context = [f"{r['name']} (Last activity: {r['pushed_at']})" for r in repos_data[:5]]

    # --- Update 2: Refined AI Persona ---
    context = f"""
    You are Aegis-Agent, a high-security GitHub Execution Assistant. 
    User's current repository context: {repos_context}.
    You operate within a secure identity shield powered by Auth0.
    
    CRITICAL INSTRUCTIONS:
    1. If the user wants to fix, mark, maintain, or create a task/issue in a repo, respond ONLY in this format: 
       ACTION: CREATE_ISSUE | REPO: repo_name | TITLE: concise_title
    2. If the user is just asking questions, answer naturally as Aegis-Agent. 
    3. Always prioritize the repository with the most recent 'Last activity' timestamp if the user asks for their latest work.
    """
    
    ai_resp = ai_model.generate_content(context + "\nUser Request: " + prompt).text

    if "ACTION: CREATE_ISSUE" in ai_resp:
        try:
            parts = ai_resp.split("|")
            repo = parts[1].split(":")[1].strip()
            title = parts[2].split(":")[1].strip()
            
            async with httpx.AsyncClient() as client:
                u_res = await client.get("https://api.github.com/user", headers={"Authorization": f"token {token}"})
                issue = await client.post(
                    f"https://api.github.com/repos/{u_res.json()['login']}/{repo}/issues",
                    headers={"Authorization": f"token {token}"},
                    json={"title": title, "body": "This task was automatically generated by Aegis-Agent via authorized identity vault."}
                )
                return {
                    "status": "success", 
                    "execution_trace": issue.json().get("html_url"), 
                    "reasoning_trace": ai_resp,
                    "identity_layer": "Shielded by Auth0"
                }
        except:
            return {"error": "Aegis-Agent encountered an error parsing the execution command."}

    return {"agent_response": ai_resp}