import os
import httpx
import google.generativeai as genai
from fastapi import FastAPI, Request
from fastapi.responses import RedirectResponse, JSONResponse, FileResponse
from dotenv import load_dotenv
from authlib.integrations.starlette_client import OAuth
from starlette.middleware.sessions import SessionMiddleware
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime

# --- 1. Environment & AI Setup ---
if not os.environ.get("RENDER"):
    load_dotenv()

# Set to '0' for Production (HTTPS required), '1' for Local
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '0'

genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
ai_model = genai.GenerativeModel('gemini-flash-latest')

app = FastAPI(title="Aegis-Agent")

# --- 2. Middleware (Order Matters) ---
app.add_middleware(
    CORSMiddleware,
    allow_origins=["https://aegis-agent-2.onrender.com"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.add_middleware(
    SessionMiddleware,
    secret_key=os.getenv("AUTH0_SECRET"),
    session_cookie="aegis_session",
    same_site="none",
    https_only=True
)

oauth = OAuth()
oauth.register(
    "auth0",
    client_id=os.getenv("AUTH0_CLIENT_ID"),
    client_secret=os.getenv("AUTH0_CLIENT_SECRET"),
    client_kwargs={"scope": "openid profile email repo offline_access"},
    server_metadata_url=f'https://{os.getenv("AUTH0_DOMAIN")}/.well-known/openid-configuration',
)

# --- 3. Token Vault (RFC 8693) ---
async def get_github_token(user_id: str, access_token: str | None):
    domain = os.getenv("AUTH0_DOMAIN")
    client_id = os.getenv("AUTH0_CLIENT_ID")
    client_secret = os.getenv("AUTH0_CLIENT_SECRET")
    
    async with httpx.AsyncClient() as client:
        # Step A: Attempt RFC 8693 Federated Token Exchange
        if access_token:
            try:
                res = await client.post(
                    f"https://{domain}/oauth/token",
                    json={
                        "client_id": client_id,
                        "client_secret": client_secret,
                        "subject_token": access_token,
                        "grant_type": "urn:auth0:params:oauth:grant-type:token-exchange:federated-connection-access-token",
                        "subject_token_type": "urn:ietf:params:oauth:token-type:access_token",
                        "requested_token_type": "http://auth0.com/oauth/token-type/federated-connection-access-token",
                        "connection": "github"
                    }
                )
                if res.status_code == 200:
                    return res.json().get("access_token")
            except Exception:
                pass

        # Step B: Management API Fallback
        try:
            m_res = await client.post(
                f"https://{domain}/oauth/token",
                json={
                    "client_id": client_id,
                    "client_secret": client_secret,
                    "audience": f"https://{domain}/api/v2/",
                    "grant_type": "client_credentials"
                }
            )
            m_token = m_res.json().get("access_token")
            u_res = await client.get(
                f"https://{domain}/api/v2/users/{user_id}",
                headers={"Authorization": f"Bearer {m_token}"}
            )
            for identity in u_res.json().get("identities", []):
                if identity.get("provider") == "github":
                    return identity.get("access_token")
        except Exception:
            return None
    return None

# --- 4. The 6 Agent Actions (The Hands) ---
async def run_action(action: str, token: str, username: str) -> dict:
    headers = {"Authorization": f"token {token}"}
    async with httpx.AsyncClient() as client:
        
        # 1. LIST_REPOS
        if "ACTION: LIST_REPOS" in action:
            res = await client.get("https://api.github.com/user/repos?sort=pushed&per_page=8", headers=headers)
            repos = [f"• {r['name']} (Last push: {r['pushed_at'][:10]})" for r in res.json()]
            return {"status": "success", "agent_response": "Found your latest repositories:\n" + "\n".join(repos)}

        # 2. CREATE_ISSUE
        if "ACTION: CREATE_ISSUE" in action:
            parts = action.split("|")
            repo = parts[1].split(":")[1].strip()
            title = parts[2].split(":")[1].strip()
            res = await client.post(f"https://api.github.com/repos/{username}/{repo}/issues", 
                                    headers=headers, json={"title": title, "body": "Generated by Aegis-Agent."})
            return {"status": "success", "execution_trace": res.json().get("html_url"), "agent_response": f"Issue created successfully in {repo}."}

        # 3. LIST_ISSUES
        if "ACTION: LIST_ISSUES" in action:
            parts = action.split("|")
            repo = parts[1].split(":")[1].strip()
            res = await client.get(f"https://api.github.com/repos/{username}/{repo}/issues?state=open", headers=headers)
            issues = [f"• #{i['number']}: {i['title']}" for i in res.json()[:5]]
            return {"status": "success", "agent_response": f"Current open issues in {repo}:\n" + ("\n".join(issues) if issues else "No open issues found.")}

        # 4. CLOSE_ISSUE (Triggers Step-Up Auth UI)
        if "ACTION: CLOSE_ISSUE" in action:
            parts = action.split("|")
            repo = parts[1].split(":")[1].strip()
            num = parts[2].split(":")[1].strip()
            return {
                "status": "step_up_required",
                "message": f"⚠ Security Protocol: Closing issue #{num} in {repo} requires manual authorization. Type 'CONFIRM:{repo}:{num}' to proceed.",
                "pending_action": action
            }

        # 5. REPO_STATS
        if "ACTION: REPO_STATS" in action:
            parts = action.split("|")
            repo = parts[1].split(":")[1].strip()
            res = await client.get(f"https://api.github.com/repos/{username}/{repo}", headers=headers)
            r = res.json()
            stats = f"📊 Repo Stats for {repo}:\nStars: {r['stargazers_count']} | Language: {r['language']} | Open Issues: {r['open_issues_count']}"
            return {"status": "success", "agent_response": stats}

        # 6. COMMENT_ISSUE
        if "ACTION: COMMENT_ISSUE" in action:
            parts = action.split("|")
            repo = parts[1].split(":")[1].strip()
            num = parts[2].split(":")[1].strip()
            msg = parts[3].split(":")[1].strip()
            await client.post(f"https://api.github.com/repos/{username}/{repo}/issues/{num}/comments", 
                             headers=headers, json={"body": msg})
            return {"status": "success", "agent_response": f"✔ Comment added to issue #{num} in {repo}."}

    return {"status": "error", "error": "Identity Shield: Action execution failed."}

# --- 5. Routes ---

@app.get("/")
def root():
    return RedirectResponse(url="/ui")

@app.get("/ui")
def serve_ui():
    possible_paths = [
        os.path.join(os.getcwd(), "frontend", "index.html"),
        os.path.join(os.getcwd(), "..", "frontend", "index.html")
    ]
    for path in possible_paths:
        if os.path.exists(path):
            return FileResponse(path)
    return JSONResponse({"error": "UI Assets Not Found"}, status_code=404)

@app.get("/status")
def check_status(request: Request):
    user = request.session.get("user")
    if user:
        return {"status": "logged_in", "name": user.get("name", "User"), "picture": user.get("picture", "")}
    return JSONResponse({"status": "unauthorized"}, status_code=401)

@app.get("/login")
async def login(request: Request):
    return await oauth.auth0.authorize_redirect(
        request, 
        redirect_uri=os.getenv("AUTH0_CALLBACK_URL"), 
        connection="github"
    )

@app.get("/callback")
async def callback(request: Request):
    try:
        token = await oauth.auth0.authorize_access_token(request)
        request.session["user"] = token.get("userinfo")
        request.session["access_token"] = token.get("access_token")
        return RedirectResponse(url="/ui")
    except Exception as e:
        return JSONResponse({"error": "Callback failed", "details": str(e)}, status_code=400)

@app.get("/logout")
def logout(request: Request):
    request.session.clear()
    return RedirectResponse(url="/ui")

@app.get("/ask-agent")
async def ask_agent(request: Request, prompt: str):
    user = request.session.get("user")
    if not user: return {"error": "Authentication Required"}

    # Handle STEP-UP Confirmation (Manual Authorization)
    if prompt.upper().startswith("CONFIRM:"):
        parts = prompt.split(":")
        repo, num = parts[1], parts[2]
        token = await get_github_token(user.get("sub"), request.session.get("access_token"))
        async with httpx.AsyncClient() as c:
            u_res = await c.get("https://api.github.com/user", headers={"Authorization": f"token {token}"})
            username = u_res.json()['login']
            await c.patch(f"https://api.github.com/repos/{username}/{repo}/issues/{num}", 
                         headers={"Authorization": f"token {token}"}, json={"state": "closed"})
            return {"status": "success", "agent_response": f"✔ SECURE CLOSE COMPLETE: Issue #{num} in {repo} is now closed."}

    # Standard Agent Flow
    token = await get_github_token(user.get("sub"), request.session.get("access_token"))
    async with httpx.AsyncClient() as client:
        u_res = await client.get("https://api.github.com/user", headers={"Authorization": f"token {token}"})
        username = u_res.json()['login']

    context = f"""You are Aegis-Agent, a secure GitHub AI assistant. 
    Time: {datetime.utcnow().strftime('%Y-%m-%d')} | User: {username}
    
    CAPABILITIES (Respond with EXACTLY the ACTION line to trigger):
    ACTION: LIST_REPOS
    ACTION: CREATE_ISSUE | REPO: name | TITLE: title
    ACTION: LIST_ISSUES | REPO: name
    ACTION: CLOSE_ISSUE | REPO: name | ISSUE: number
    ACTION: REPO_STATS | REPO: name
    ACTION: COMMENT_ISSUE | REPO: name | ISSUE: number | MSG: text

    SECURITY PROTOCOLS:
    - Destructive actions (like CLOSE_ISSUE) must be triggered via the ACTION line.
    - If task matches an ACTION, reply with ONLY that line.
    - For general chat, remain professional and security-conscious."""

    ai_resp = ai_model.generate_content(context + "\nUser: " + prompt).text.strip()

    # Robust Action Parsing
    for line in ai_resp.split('\n'):
        if "ACTION:" in line:
            res = await run_action(line, token, username)
            res["reasoning_trace"] = line
            return res

    return {"agent_response": ai_resp}